<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="56" passed="38" failed="16" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-15T21:17:29 CEST" name="PositiveLoginTestSuite" finished-at="2021-09-15T21:17:58 CEST" duration-ms="29492">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:17:29 CEST" name="PositiveLoginOnMainPageTest1-CH" finished-at="2021-09-15T21:17:41 CEST" duration-ms="12291">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:29 CEST" name="setUp" finished-at="2021-09-15T21:17:30 CEST" duration-ms="1362" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@43094e0c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:30 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:17:32 CEST" duration-ms="2144" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:32 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:33 CEST" duration-ms="629" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:33 CEST" name="setUp" finished-at="2021-09-15T21:17:34 CEST" duration-ms="1313" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@43094e0c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:34 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:17:35 CEST" duration-ms="793" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:35 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:36 CEST" duration-ms="619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:36 CEST" name="setUp" finished-at="2021-09-15T21:17:37 CEST" duration-ms="1305" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@43094e0c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:37 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:17:37 CEST" duration-ms="511" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:38 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:38 CEST" duration-ms="624" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:38 CEST" name="setUp" finished-at="2021-09-15T21:17:40 CEST" duration-ms="1314" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@43094e0c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:40 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:17:40 CEST" duration-ms="477" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@4331d187]" started-at="2021-09-15T21:17:40 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:41 CEST" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveLoginTests -->
    </test> <!-- PositiveLoginOnMainPageTest1-CH -->
    <test started-at="2021-09-15T21:17:41 CEST" name="PositiveLoginOnMainPageTest2-FF" finished-at="2021-09-15T21:17:58 CEST" duration-ms="17187">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:41 CEST" name="setUp" finished-at="2021-09-15T21:17:44 CEST" duration-ms="2973" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17e8c38c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:44 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:17:45 CEST" duration-ms="1134" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:45 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:46 CEST" duration-ms="606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:46 CEST" name="setUp" finished-at="2021-09-15T21:17:49 CEST" duration-ms="2972" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17e8c38c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:49 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:17:49 CEST" duration-ms="612" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:49 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:50 CEST" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:50 CEST" name="setUp" finished-at="2021-09-15T21:17:53 CEST" duration-ms="2978" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17e8c38c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:53 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:17:53 CEST" duration-ms="473" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:53 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:54 CEST" duration-ms="596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:54 CEST" name="setUp" finished-at="2021-09-15T21:17:57 CEST" duration-ms="2971" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17e8c38c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:57 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:17:57 CEST" duration-ms="448" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@1a20270e]" started-at="2021-09-15T21:17:58 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:58 CEST" duration-ms="596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveLoginTests -->
    </test> <!-- PositiveLoginOnMainPageTest2-FF -->
  </suite> <!-- PositiveLoginTestSuite -->
  <suite started-at="2021-09-15T21:18:12 CEST" name="NegativeLoginUsernameOnMainPageTestSuite" finished-at="2021-09-15T21:18:55 CEST" duration-ms="42598">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:18:12 CEST" name="NegativeLoginTest-CH" finished-at="2021-09-15T21:18:30 CEST" duration-ms="17375">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:12 CEST" name="setUp" finished-at="2021-09-15T21:18:14 CEST" duration-ms="1283" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5c4516ec]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:14 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:18:16 CEST" duration-ms="2273" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:16 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:17 CEST" duration-ms="612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:17 CEST" name="setUp" finished-at="2021-09-15T21:18:18 CEST" duration-ms="1273" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5c4516ec]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:18 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:18:19 CEST" duration-ms="737" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:19 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:19 CEST" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:19 CEST" name="setUp" finished-at="2021-09-15T21:18:21 CEST" duration-ms="1342" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5c4516ec]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:21 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:18:21 CEST" duration-ms="759" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:21 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:22 CEST" duration-ms="607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:22 CEST" name="setUp" finished-at="2021-09-15T21:18:23 CEST" duration-ms="1323" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5c4516ec]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:23 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:18:24 CEST" duration-ms="508" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:24 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:25 CEST" duration-ms="619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:25 CEST" name="setUp" finished-at="2021-09-15T21:18:26 CEST" duration-ms="1259" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5c4516ec]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:26 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:18:26 CEST" duration-ms="614" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:27 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:27 CEST" duration-ms="636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:27 CEST" name="setUp" finished-at="2021-09-15T21:18:29 CEST" duration-ms="1320" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5c4516ec]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:29 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:18:29 CEST" duration-ms="457" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@72437d8d]" started-at="2021-09-15T21:18:29 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:30 CEST" duration-ms="621" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeLoginTests -->
    </test> <!-- NegativeLoginTest-CH -->
    <test started-at="2021-09-15T21:18:30 CEST" name="NegativeLoginTest-FF" finished-at="2021-09-15T21:18:55 CEST" duration-ms="25205">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:30 CEST" name="setUp" finished-at="2021-09-15T21:18:33 CEST" duration-ms="2992" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17ea3bc0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:33 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:18:33 CEST" duration-ms="599" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:33 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:34 CEST" duration-ms="598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:34 CEST" name="setUp" finished-at="2021-09-15T21:18:37 CEST" duration-ms="2953" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17ea3bc0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:37 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:18:38 CEST" duration-ms="543" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:38 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:38 CEST" duration-ms="606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:38 CEST" name="setUp" finished-at="2021-09-15T21:18:41 CEST" duration-ms="2947" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17ea3bc0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:41 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-15T21:18:42 CEST" duration-ms="625" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:42 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:42 CEST" duration-ms="769" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:42 CEST" name="setUp" finished-at="2021-09-15T21:18:45 CEST" duration-ms="2964" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17ea3bc0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:45 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:18:46 CEST" duration-ms="422" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:46 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:47 CEST" duration-ms="755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:47 CEST" name="setUp" finished-at="2021-09-15T21:18:50 CEST" duration-ms="2980" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17ea3bc0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:50 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:18:50 CEST" duration-ms="426" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:50 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:51 CEST" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:51 CEST" name="setUp" finished-at="2021-09-15T21:18:54 CEST" duration-ms="2975" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@17ea3bc0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:54 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-15T21:18:54 CEST" duration-ms="428" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@29a0cdb]" started-at="2021-09-15T21:18:54 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:55 CEST" duration-ms="694" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeLoginTests -->
    </test> <!-- NegativeLoginTest-FF -->
  </suite> <!-- NegativeLoginUsernameOnMainPageTestSuite -->
  <suite started-at="2021-09-15T21:17:08 CEST" name="FindByUsernameTestSuite" finished-at="2021-09-15T21:17:08 CEST" duration-ms="194">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:17:08 CEST" name="FindByUsernameTests" finished-at="2021-09-15T21:17:08 CEST" duration-ms="194">
      <class name="local.HLVTestApp.APITests.API_FindByUsernameTests">
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@38089a5a]" started-at="2021-09-15T21:17:08 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="41" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, bodyFirstName=firstName":"test1, description=get user - valid 1, bodyLastName=lastName":"test1, username=test1, statusCode=200, bodyUsername=username":"test1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@38089a5a]" started-at="2021-09-15T21:17:08 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="17" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, bodyFirstName=firstName":"test2, description=get user - valid 2, bodyLastName=lastName":"test2, username=test2, statusCode=200, bodyUsername=username":"test2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@38089a5a]" started-at="2021-09-15T21:17:08 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="14" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, bodyFirstName=firstName":"test3, description=get user - valid 3, bodyLastName=lastName":"test3, username=test3, statusCode=200, bodyUsername=username":"test3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@38089a5a]" started-at="2021-09-15T21:17:08 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, bodyFirstName=, description=Login with invalid username, bodyLastName=, username=invalidUsername, statusCode=404, bodyUsername=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@38089a5a]" started-at="2021-09-15T21:17:08 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="108" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=5, bodyFirstName=, description=Empty username, bodyLastName=, username=, statusCode=404, bodyUsername=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
      </class> <!-- local.HLVTestApp.APITests.API_FindByUsernameTests -->
    </test> <!-- FindByUsernameTests -->
  </suite> <!-- FindByUsernameTestSuite -->
  <suite started-at="2021-09-15T21:19:15 CEST" name="AllAPITestSuites" finished-at="2021-09-15T21:19:15 CEST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- AllAPITestSuites -->
  <suite started-at="2021-09-15T21:19:15 CEST" name="AllGUITestSuites" finished-at="2021-09-15T21:19:15 CEST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- AllGUITestSuites -->
  <suite started-at="2021-09-15T21:19:15 CEST" name="ValidateLoginTestSuite" finished-at="2021-09-15T21:19:15 CEST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- ValidateLoginTestSuite -->
  <suite started-at="2021-09-15T21:17:58 CEST" name="NegativeSignUpTestSuite" finished-at="2021-09-15T21:18:12 CEST" duration-ms="14262">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:17:58 CEST" name="FailedUserRegistrationTest1-CH" finished-at="2021-09-15T21:18:04 CEST" duration-ms="5699">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@4b79ac84]" started-at="2021-09-15T21:17:58 CEST" name="setUp" finished-at="2021-09-15T21:18:00 CEST" duration-ms="1343" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4d93e5bf]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@4b79ac84]" started-at="2021-09-15T21:18:00 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-15T21:18:00 CEST" duration-ms="952" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=testFirstName1, lastName=testLastName1, password=testPassword1, mobile=testMobile1, email=test1@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@4b79ac84]" started-at="2021-09-15T21:18:00 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:01 CEST" duration-ms="604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@4b79ac84]" started-at="2021-09-15T21:18:01 CEST" name="setUp" finished-at="2021-09-15T21:18:02 CEST" duration-ms="1247" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4d93e5bf]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@4b79ac84]" started-at="2021-09-15T21:18:02 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-15T21:18:03 CEST" duration-ms="951" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=testFirstName2, lastName=testLastName2, password=testPassword2, mobile=testMobile2, email=test2@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@4b79ac84]" started-at="2021-09-15T21:18:03 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:04 CEST" duration-ms="599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeSignUpTests -->
    </test> <!-- FailedUserRegistrationTest1-CH -->
    <test started-at="2021-09-15T21:18:04 CEST" name="FailedUserRegistrationTest2-FF" finished-at="2021-09-15T21:18:12 CEST" duration-ms="8553">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@5460cf3a]" started-at="2021-09-15T21:18:04 CEST" name="setUp" finished-at="2021-09-15T21:18:07 CEST" duration-ms="2985" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@1c36ab22]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@5460cf3a]" started-at="2021-09-15T21:18:07 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-15T21:18:07 CEST" duration-ms="557" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=testFirstName1, lastName=testLastName1, password=testPassword1, mobile=testMobile1, email=test1@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@5460cf3a]" started-at="2021-09-15T21:18:07 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:08 CEST" duration-ms="608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@5460cf3a]" started-at="2021-09-15T21:18:08 CEST" name="setUp" finished-at="2021-09-15T21:18:11 CEST" duration-ms="2973" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@1c36ab22]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@5460cf3a]" started-at="2021-09-15T21:18:11 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-15T21:18:12 CEST" duration-ms="650" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=testFirstName2, lastName=testLastName2, password=testPassword2, mobile=testMobile2, email=test2@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@5460cf3a]" started-at="2021-09-15T21:18:12 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:12 CEST" duration-ms="773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeSignUpTests -->
    </test> <!-- FailedUserRegistrationTest2-FF -->
  </suite> <!-- NegativeSignUpTestSuite -->
  <suite started-at="2021-09-15T21:17:09 CEST" name="PositiveSignUpTestSuite" finished-at="2021-09-15T21:17:29 CEST" duration-ms="20126">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:17:09 CEST" name="UserRegistrationTest1-CH" finished-at="2021-09-15T21:17:19 CEST" duration-ms="10908">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@77102b91]" started-at="2021-09-15T21:17:09 CEST" name="setUp" finished-at="2021-09-15T21:17:11 CEST" duration-ms="2779" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@68303c3e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionChrome(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@77102b91]" started-at="2021-09-15T21:17:11 CEST" name="verifySuccessfulSignUpActionChrome" data-provider="csvReader" finished-at="2021-09-15T21:17:16 CEST" duration-ms="4209" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=testFirstName1, lastName=testLastName1, password=testPassword1, mobile=testMobile1, email=test1@hlv.com, expectedMessage=User has been successfully registered., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionChrome -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@77102b91]" started-at="2021-09-15T21:17:16 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:16 CEST" duration-ms="781" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@77102b91]" started-at="2021-09-15T21:17:16 CEST" name="setUp" finished-at="2021-09-15T21:17:18 CEST" duration-ms="1288" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@68303c3e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionChrome(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@77102b91]" started-at="2021-09-15T21:17:18 CEST" name="verifySuccessfulSignUpActionChrome" data-provider="csvReader" finished-at="2021-09-15T21:17:19 CEST" duration-ms="1179" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=testFirstName2, lastName=testLastName2, password=testPassword2, mobile=testMobile2, email=test2@hlv.com, expectedMessage=User has been successfully registered., username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionChrome -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@77102b91]" started-at="2021-09-15T21:17:19 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:19 CEST" duration-ms="668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveSignUpTests -->
    </test> <!-- UserRegistrationTest1-CH -->
    <test started-at="2021-09-15T21:17:19 CEST" name="UserRegistrationTest2-FF" finished-at="2021-09-15T21:17:29 CEST" duration-ms="9214">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@6bffbc6d]" started-at="2021-09-15T21:17:19 CEST" name="setUp" finished-at="2021-09-15T21:17:23 CEST" duration-ms="3756" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@2ec23ec3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionFirefox(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@6bffbc6d]" started-at="2021-09-15T21:17:23 CEST" name="verifySuccessfulSignUpActionFirefox" data-provider="csvReader" finished-at="2021-09-15T21:17:24 CEST" duration-ms="691" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, firstName=testFirstName3, lastName=testLastName3, password=testPassword3, mobile=testMobile3, email=test3@hlv.com, expectedMessage=User has been successfully registered., username=testUsername3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionFirefox -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@6bffbc6d]" started-at="2021-09-15T21:17:24 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:25 CEST" duration-ms="624" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@6bffbc6d]" started-at="2021-09-15T21:17:25 CEST" name="setUp" finished-at="2021-09-15T21:17:28 CEST" duration-ms="2979" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@2ec23ec3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionFirefox(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@6bffbc6d]" started-at="2021-09-15T21:17:28 CEST" name="verifySuccessfulSignUpActionFirefox" data-provider="csvReader" finished-at="2021-09-15T21:17:28 CEST" duration-ms="557" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, firstName=testFirstName4, lastName=testLastName4, password=testPassword4, mobile=testMobile4, email=test4@hlv.com, expectedMessage=User has been successfully registered., username=testUsername4}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionFirefox -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@6bffbc6d]" started-at="2021-09-15T21:17:28 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:17:29 CEST" duration-ms="604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveSignUpTests -->
    </test> <!-- UserRegistrationTest2-FF -->
  </suite> <!-- PositiveSignUpTestSuite -->
  <suite started-at="2021-09-15T21:17:08 CEST" name="DeleteAllUsersTestSuite" finished-at="2021-09-15T21:17:09 CEST" duration-ms="37">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:17:08 CEST" name="DeleteAllUsersTests" finished-at="2021-09-15T21:17:09 CEST" duration-ms="37">
      <class name="local.HLVTestApp.APITests.API_DeleteAllUsersTests">
        <test-method signature="API_DeleteAllUsers(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteAllUsersTests@39de3d36]" started-at="2021-09-15T21:17:08 CEST" name="API_DeleteAllUsers" data-provider="csvReader" finished-at="2021-09-15T21:17:09 CEST" duration-ms="33" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=Delete all users, body=All users removed, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteAllUsers -->
      </class> <!-- local.HLVTestApp.APITests.API_DeleteAllUsersTests -->
    </test> <!-- DeleteAllUsersTests -->
  </suite> <!-- DeleteAllUsersTestSuite -->
  <suite started-at="2021-09-15T21:17:08 CEST" name="DeleteByUsernameTestSuite" finished-at="2021-09-15T21:17:08 CEST" duration-ms="107">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:17:08 CEST" name="DeleteByUsernameTests" finished-at="2021-09-15T21:17:08 CEST" duration-ms="107">
      <class name="local.HLVTestApp.APITests.API_DeleteByUsernameTests">
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@13ad5cd3]" started-at="2021-09-15T21:17:08 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="47" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=delete user - valid 1, body=User with username test1 is removed, username=test1, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@13ad5cd3]" started-at="2021-09-15T21:17:08 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="16" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=delete user - valid 2, body=User with username test2 is removed, username=test2, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@13ad5cd3]" started-at="2021-09-15T21:17:08 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="15" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=delete user - valid 3, body=User with username test3 is removed, username=test3, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@13ad5cd3]" started-at="2021-09-15T21:17:08 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="9" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, description=, body=, username=invalidUsername, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@13ad5cd3]" started-at="2021-09-15T21:17:08 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="14" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=5, description=, body=, username=, statusCode=404}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
      </class> <!-- local.HLVTestApp.APITests.API_DeleteByUsernameTests -->
    </test> <!-- DeleteByUsernameTests -->
  </suite> <!-- DeleteByUsernameTestSuite -->
  <suite started-at="2021-09-15T21:18:55 CEST" name="ExternalLoginLinkTestSuite" finished-at="2021-09-15T21:19:15 CEST" duration-ms="19586">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:18:55 CEST" name="ExternalLoginLinkTest1-CH" finished-at="2021-09-15T21:19:02 CEST" duration-ms="7420">
      <class name="local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:18:55 CEST" name="setUp" finished-at="2021-09-15T21:18:56 CEST" duration-ms="1326" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@7c2e88b9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:18:56 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-15T21:18:57 CEST" duration-ms="336" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.facebook.com/, no=1, socialNetwork=Facebook}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:18:57 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:18:58 CEST" duration-ms="677" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:18:58 CEST" name="setUp" finished-at="2021-09-15T21:18:59 CEST" duration-ms="1308" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@7c2e88b9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:18:59 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-15T21:18:59 CEST" duration-ms="396" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://twitter.com/, no=2, socialNetwork=Twitter}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://twitter.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://twitter.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:18:59 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:19:00 CEST" duration-ms="673" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:19:00 CEST" name="setUp" finished-at="2021-09-15T21:19:01 CEST" duration-ms="1288" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@7c2e88b9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:19:01 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-15T21:19:02 CEST" duration-ms="241" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.plus.google.com/, no=3, socialNetwork=GooglePlus}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.plus.google.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.plus.google.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@4ed5eb72]" started-at="2021-09-15T21:19:02 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:19:02 CEST" duration-ms="638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests -->
    </test> <!-- ExternalLoginLinkTest1-CH -->
    <test started-at="2021-09-15T21:19:02 CEST" name="ExternalLoginLinkTest2-FF" finished-at="2021-09-15T21:19:15 CEST" duration-ms="12157">
      <class name="local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:02 CEST" name="setUp" finished-at="2021-09-15T21:19:05 CEST" duration-ms="2941" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@3c5044fa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:05 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-15T21:19:06 CEST" duration-ms="332" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.facebook.com/, no=1, socialNetwork=Facebook}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:06 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:19:07 CEST" duration-ms="713" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:07 CEST" name="setUp" finished-at="2021-09-15T21:19:10 CEST" duration-ms="2972" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@3c5044fa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:10 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-15T21:19:10 CEST" duration-ms="312" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://twitter.com/, no=2, socialNetwork=Twitter}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://twitter.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://twitter.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:10 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:19:11 CEST" duration-ms="634" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:11 CEST" name="setUp" finished-at="2021-09-15T21:19:14 CEST" duration-ms="2964" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@3c5044fa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:14 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-15T21:19:14 CEST" duration-ms="351" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.plus.google.com/, no=3, socialNetwork=GooglePlus}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.plus.google.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.plus.google.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@40db2a24]" started-at="2021-09-15T21:19:14 CEST" name="tearDownAfterEach" finished-at="2021-09-15T21:19:15 CEST" duration-ms="619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests -->
    </test> <!-- ExternalLoginLinkTest2-FF -->
  </suite> <!-- ExternalLoginLinkTestSuite -->
  <suite started-at="2021-09-15T21:19:15 CEST" name="HLV App Test Suites" finished-at="2021-09-15T21:19:15 CEST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- HLV App Test Suites -->
  <suite started-at="2021-09-15T21:17:05 CEST" name="RegisterUserTestSuite" finished-at="2021-09-15T21:17:08 CEST" duration-ms="2946">
    <groups>
    </groups>
    <test started-at="2021-09-15T21:17:05 CEST" name="RegisterUserTests" finished-at="2021-09-15T21:17:08 CEST" duration-ms="2946">
      <class name="local.HLVTestApp.APITests.API_RegisterUserTests">
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:05 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="2739" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=test1, lastName=test1, password=test1, description=valid username and password, body=, username=test1, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="34" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=test11111111111111111111111, lastName=test11, password=test11, description=Too long first name, body=First Name should be less than 15, username=test11, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="16" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, firstName=test111, lastName=test11111111111111111111111, password=test111, description=Too long last name, body=LAst Name should be less than 15, username=test111, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="26" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, firstName=test1111, lastName=test1111, password=test1111, description=User already exist, body=User with the specified username already exists!, username=test1, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="12" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=5, firstName=test11111, lastName=test11111, password=test11111, description=Too long username, body=Username must not be longer that 50 characters or shorter than 6 characters., username=test11111111111111111111111111111111111111111111111111111111, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="20" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=6, firstName=test2, lastName=test2, password=test2, description=valid username and password 2, body=, username=test2, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="14" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=7, firstName=test3, lastName=test3, password=test3, description=valid username and password 3, body=, username=test3, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="17" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=8, firstName=test4, lastName=test4, password=test4, description=valid username and password 4, body=, username=test4, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@c7ba306]" started-at="2021-09-15T21:17:08 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-15T21:17:08 CEST" duration-ms="11" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=9, firstName=test5, lastName=test5, password=test5, description=valid username and password 5, body=, username=test5, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
      </class> <!-- local.HLVTestApp.APITests.API_RegisterUserTests -->
    </test> <!-- RegisterUserTests -->
  </suite> <!-- RegisterUserTestSuite -->
</testng-results>
