<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="65" passed="45" failed="18" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-16T17:35:48 CEST" name="PositiveLoginTestSuite" finished-at="2021-09-16T17:36:16 CEST" duration-ms="27909">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:35:48 CEST" name="PositiveLoginOnMainPageTest1-CH" finished-at="2021-09-16T17:35:59 CEST" duration-ms="11589">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:48 CEST" name="setUp" finished-at="2021-09-16T17:35:49 CEST" duration-ms="1356" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@772bc4c9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:49 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:35:51 CEST" duration-ms="2058" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:51 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:52 CEST" duration-ms="636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:52 CEST" name="setUp" finished-at="2021-09-16T17:35:53 CEST" duration-ms="1282" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@772bc4c9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:53 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:35:54 CEST" duration-ms="646" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:54 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:54 CEST" duration-ms="613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:54 CEST" name="setUp" finished-at="2021-09-16T17:35:56 CEST" duration-ms="1298" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@772bc4c9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:56 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:35:56 CEST" duration-ms="366" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:56 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:57 CEST" duration-ms="683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:57 CEST" name="setUp" finished-at="2021-09-16T17:35:58 CEST" duration-ms="1292" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@772bc4c9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:58 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:35:59 CEST" duration-ms="377" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@5bf8fa12]" started-at="2021-09-16T17:35:59 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:59 CEST" duration-ms="616" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveLoginTests -->
    </test> <!-- PositiveLoginOnMainPageTest1-CH -->
    <test started-at="2021-09-16T17:35:59 CEST" name="PositiveLoginOnMainPageTest2-FF" finished-at="2021-09-16T17:36:16 CEST" duration-ms="16312">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:35:59 CEST" name="setUp" finished-at="2021-09-16T17:36:02 CEST" duration-ms="2930" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@152dbf8e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:02 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:03 CEST" duration-ms="488" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:03 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:03 CEST" duration-ms="660" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:03 CEST" name="setUp" finished-at="2021-09-16T17:36:06 CEST" duration-ms="2977" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@152dbf8e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:06 CEST" name="verifySuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:07 CEST" duration-ms="536" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:07 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:08 CEST" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:08 CEST" name="setUp" finished-at="2021-09-16T17:36:11 CEST" duration-ms="2968" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@152dbf8e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:11 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:36:11 CEST" duration-ms="283" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=valid username and password 1, password=testPassword1, username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:11 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:12 CEST" duration-ms="744" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:12 CEST" name="setUp" finished-at="2021-09-16T17:36:15 CEST" duration-ms="2958" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@152dbf8e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:15 CEST" name="verifySuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:36:15 CEST" duration-ms="326" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=valid username and password 2, password=testPassword2, username=testUsername2}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername2&password=testPassword2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfulLoginActionOnMainPage(PositiveLoginTests.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveLoginTests@34158c08]" started-at="2021-09-16T17:36:15 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:16 CEST" duration-ms="618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveLoginTests -->
    </test> <!-- PositiveLoginOnMainPageTest2-FF -->
  </suite> <!-- PositiveLoginTestSuite -->
  <suite started-at="2021-09-16T17:36:29 CEST" name="NegativeLoginUsernameOnMainPageTestSuite" finished-at="2021-09-16T17:37:11 CEST" duration-ms="42039">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:36:29 CEST" name="NegativeLoginTest-CH" finished-at="2021-09-16T17:36:47 CEST" duration-ms="17777">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:29 CEST" name="setUp" finished-at="2021-09-16T17:36:31 CEST" duration-ms="1278" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@34ea86ff]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:31 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:34 CEST" duration-ms="3300" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:34 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:35 CEST" duration-ms="622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:35 CEST" name="setUp" finished-at="2021-09-16T17:36:36 CEST" duration-ms="1266" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@34ea86ff]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:36 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:37 CEST" duration-ms="695" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:37 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:37 CEST" duration-ms="609" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:37 CEST" name="setUp" finished-at="2021-09-16T17:36:38 CEST" duration-ms="1293" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@34ea86ff]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:38 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:39 CEST" duration-ms="678" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:39 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:40 CEST" duration-ms="609" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:40 CEST" name="setUp" finished-at="2021-09-16T17:36:41 CEST" duration-ms="1275" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@34ea86ff]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:41 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:36:41 CEST" duration-ms="404" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:42 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:42 CEST" duration-ms="622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:42 CEST" name="setUp" finished-at="2021-09-16T17:36:43 CEST" duration-ms="1243" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@34ea86ff]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:43 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:36:44 CEST" duration-ms="383" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:44 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:45 CEST" duration-ms="631" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:45 CEST" name="setUp" finished-at="2021-09-16T17:36:46 CEST" duration-ms="1266" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@34ea86ff]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:46 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:36:46 CEST" duration-ms="394" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@335b5620]" started-at="2021-09-16T17:36:47 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:47 CEST" duration-ms="631" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeLoginTests -->
    </test> <!-- NegativeLoginTest-CH -->
    <test started-at="2021-09-16T17:36:47 CEST" name="NegativeLoginTest-FF" finished-at="2021-09-16T17:37:11 CEST" duration-ms="24243">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeLoginTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:47 CEST" name="setUp" finished-at="2021-09-16T17:36:50 CEST" duration-ms="2952" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4bcf08ae]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:50 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:51 CEST" duration-ms="538" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:51 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:51 CEST" duration-ms="604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:51 CEST" name="setUp" finished-at="2021-09-16T17:36:54 CEST" duration-ms="2984" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4bcf08ae]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:54 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:55 CEST" duration-ms="486" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:55 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:55 CEST" duration-ms="582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:55 CEST" name="setUp" finished-at="2021-09-16T17:36:58 CEST" duration-ms="2954" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4bcf08ae]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnLoginPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:58 CEST" name="verifyUnsuccessfulLoginActionOnLoginPage" data-provider="csvReader" finished-at="2021-09-16T17:36:59 CEST" duration-ms="523" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnLoginPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:59 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:59 CEST" duration-ms="640" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:36:59 CEST" name="setUp" finished-at="2021-09-16T17:37:02 CEST" duration-ms="2983" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4bcf08ae]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:02 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:37:03 CEST" duration-ms="307" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=incorrect username, password=testPassword1, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:03 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:03 CEST" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:03 CEST" name="setUp" finished-at="2021-09-16T17:37:06 CEST" duration-ms="2933" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4bcf08ae]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:06 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:37:07 CEST" duration-ms="316" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=incorrect password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:07 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:07 CEST" duration-ms="621" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:07 CEST" name="setUp" finished-at="2021-09-16T17:37:10 CEST" duration-ms="2942" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4bcf08ae]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulLoginActionOnMainPage(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:10 CEST" name="verifyUnsuccessfulLoginActionOnMainPage" data-provider="csvReader" finished-at="2021-09-16T17:37:11 CEST" duration-ms="322" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=incorrect username and password, password=incorrectPassword, expectedMessage=Invalid Email. Try again., username=incorrectUsername}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeLoginTests@3c9c0d96]" started-at="2021-09-16T17:37:11 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:11 CEST" duration-ms="627" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeLoginTests -->
    </test> <!-- NegativeLoginTest-FF -->
  </suite> <!-- NegativeLoginUsernameOnMainPageTestSuite -->
  <suite started-at="2021-09-16T17:35:28 CEST" name="FindByUsernameTestSuite" finished-at="2021-09-16T17:35:28 CEST" duration-ms="218">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:35:28 CEST" name="FindByUsernameTests" finished-at="2021-09-16T17:35:28 CEST" duration-ms="218">
      <class name="local.HLVTestApp.APITests.API_FindByUsernameTests">
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@4f0100a7]" started-at="2021-09-16T17:35:28 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="40" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, bodyFirstName=firstName":"test1, description=get user - valid 1, bodyLastName=lastName":"test1, username=test1, statusCode=200, bodyUsername=username":"test1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@4f0100a7]" started-at="2021-09-16T17:35:28 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="14" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, bodyFirstName=firstName":"test2, description=get user - valid 2, bodyLastName=lastName":"test2, username=test2, statusCode=200, bodyUsername=username":"test2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@4f0100a7]" started-at="2021-09-16T17:35:28 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="20" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, bodyFirstName=firstName":"test3, description=get user - valid 3, bodyLastName=lastName":"test3, username=test3, statusCode=200, bodyUsername=username":"test3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@4f0100a7]" started-at="2021-09-16T17:35:28 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="16" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, bodyFirstName=, description=Login with invalid username, bodyLastName=, username=invalidUsername, statusCode=404, bodyUsername=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
        <test-method signature="API_FindByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_FindByUsernameTests@4f0100a7]" started-at="2021-09-16T17:35:28 CEST" name="API_FindByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="123" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=5, bodyFirstName=, description=Empty username, bodyLastName=, username=, statusCode=404, bodyUsername=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_FindByUsername -->
      </class> <!-- local.HLVTestApp.APITests.API_FindByUsernameTests -->
    </test> <!-- FindByUsernameTests -->
  </suite> <!-- FindByUsernameTestSuite -->
  <suite started-at="2021-09-16T17:37:31 CEST" name="AllAPITestSuites" finished-at="2021-09-16T17:37:31 CEST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- AllAPITestSuites -->
  <suite started-at="2021-09-16T17:37:31 CEST" name="AllGUITestSuites" finished-at="2021-09-16T17:37:31 CEST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- AllGUITestSuites -->
  <suite started-at="2021-09-16T17:35:27 CEST" name="ValidateLoginTestSuite" finished-at="2021-09-16T17:35:28 CEST" duration-ms="534">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:35:27 CEST" name="ValidateLoginTests" finished-at="2021-09-16T17:35:28 CEST" duration-ms="534">
      <class name="local.HLVTestApp.APITests.API_ValidateLoginTests">
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="23" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=test1, lastName=test1, password=test1, description=successful login 1, body=, username=test1, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="12" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=test2, lastName=test2, password=test2, description=successful login 2, body=, username=test2, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, firstName=test3, lastName=test3, password=test3, description=successful login 3, body=, username=test3, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="15" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, firstName=test4, lastName=test4, password=test4, description=successful login 4, body=, username=test4, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="15" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=5, firstName=test5, lastName=test5, password=test5, description=successful login 5, body=, username=test5, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="25" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=6, firstName=incorrectFirstName, lastName=test1, password=test1, description=Login failed - Incorrect firstName, body=Login failed., username=test1, statusCode=417}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [417] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [417] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at local.HLVTestApp.APITests.API_ValidateLoginTests.API_ValidateLogin(API_ValidateLoginTests.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="24" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=7, firstName=test1, lastName=incorrectLastName, password=test1, description=Login failed - Incorrect lastName, body=Login failed., username=test1, statusCode=417}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [417] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [417] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at local.HLVTestApp.APITests.API_ValidateLoginTests.API_ValidateLogin(API_ValidateLoginTests.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="15" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=8, firstName=test1, lastName=test1, password=incorrectPassword, description=Login failed - Incorrect password, body=Login failed., username=test1, statusCode=417}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
        <test-method signature="API_ValidateLogin(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_ValidateLoginTests@9ebe38b]" started-at="2021-09-16T17:35:27 CEST" name="API_ValidateLogin" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="12" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=9, firstName=test1, lastName=test1, password=test1, description=Login failed - Incorrect username, body=Login failed., username=incorrectUsername, statusCode=417}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_ValidateLogin -->
      </class> <!-- local.HLVTestApp.APITests.API_ValidateLoginTests -->
    </test> <!-- ValidateLoginTests -->
  </suite> <!-- ValidateLoginTestSuite -->
  <suite started-at="2021-09-16T17:36:16 CEST" name="NegativeSignUpTestSuite" finished-at="2021-09-16T17:36:29 CEST" duration-ms="13655">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:36:16 CEST" name="FailedUserRegistrationTest1-CH" finished-at="2021-09-16T17:36:21 CEST" duration-ms="5405">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@2766ca9d]" started-at="2021-09-16T17:36:16 CEST" name="setUp" finished-at="2021-09-16T17:36:17 CEST" duration-ms="1336" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@626b9092]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@2766ca9d]" started-at="2021-09-16T17:36:17 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-16T17:36:18 CEST" duration-ms="763" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=testFirstName1, lastName=testLastName1, password=testPassword1, mobile=testMobile1, description=Failed to Sign Up for existing user 1, email=test1@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@2766ca9d]" started-at="2021-09-16T17:36:18 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:18 CEST" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@2766ca9d]" started-at="2021-09-16T17:36:18 CEST" name="setUp" finished-at="2021-09-16T17:36:20 CEST" duration-ms="1381" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@626b9092]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@2766ca9d]" started-at="2021-09-16T17:36:20 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-16T17:36:21 CEST" duration-ms="707" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=testFirstName2, lastName=testLastName2, password=testPassword2, mobile=testMobile2, description=Failed to Sign Up for existing user 2, email=test2@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@2766ca9d]" started-at="2021-09-16T17:36:21 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:21 CEST" duration-ms="603" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeSignUpTests -->
    </test> <!-- FailedUserRegistrationTest1-CH -->
    <test started-at="2021-09-16T17:36:21 CEST" name="FailedUserRegistrationTest2-FF" finished-at="2021-09-16T17:36:29 CEST" duration-ms="8242">
      <class name="local.HLVTestApp.loginandsignuptests.NegativeSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@6d025197]" started-at="2021-09-16T17:36:21 CEST" name="setUp" finished-at="2021-09-16T17:36:24 CEST" duration-ms="2964" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@1ac2829e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@6d025197]" started-at="2021-09-16T17:36:24 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-16T17:36:25 CEST" duration-ms="494" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=testFirstName1, lastName=testLastName1, password=testPassword1, mobile=testMobile1, description=Failed to Sign Up for existing user 1, email=test1@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@6d025197]" started-at="2021-09-16T17:36:25 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:25 CEST" duration-ms="783" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@6d025197]" started-at="2021-09-16T17:36:25 CEST" name="setUp" finished-at="2021-09-16T17:36:28 CEST" duration-ms="2952" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@1ac2829e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUnsuccessfulSignUpAction(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@6d025197]" started-at="2021-09-16T17:36:28 CEST" name="verifyUnsuccessfulSignUpAction" description="User already exist" data-provider="csvReader" finished-at="2021-09-16T17:36:29 CEST" duration-ms="426" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=testFirstName2, lastName=testLastName2, password=testPassword2, mobile=testMobile2, description=Failed to Sign Up for existing user 2, email=test2@hlv.com, expectedMessage=Oops! There is already a user registered with the email provided., username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUnsuccessfulSignUpAction -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.NegativeSignUpTests@6d025197]" started-at="2021-09-16T17:36:29 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:36:29 CEST" duration-ms="617" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.NegativeSignUpTests -->
    </test> <!-- FailedUserRegistrationTest2-FF -->
  </suite> <!-- NegativeSignUpTestSuite -->
  <suite started-at="2021-09-16T17:35:28 CEST" name="PositiveSignUpTestSuite" finished-at="2021-09-16T17:35:48 CEST" duration-ms="19852">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:35:28 CEST" name="UserRegistrationTest1-CH" finished-at="2021-09-16T17:35:39 CEST" duration-ms="10802">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@7331196b]" started-at="2021-09-16T17:35:28 CEST" name="setUp" finished-at="2021-09-16T17:35:31 CEST" duration-ms="3195" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@7a7f2247]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionChrome(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@7331196b]" started-at="2021-09-16T17:35:31 CEST" name="verifySuccessfulSignUpActionChrome" data-provider="csvReader" finished-at="2021-09-16T17:35:35 CEST" duration-ms="3895" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=testFirstName1, lastName=testLastName1, password=testPassword1, mobile=testMobile1, description=Successfully registered user 1, email=test1@hlv.com, expectedMessage=User has been successfully registered., username=testUsername1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionChrome -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@7331196b]" started-at="2021-09-16T17:35:35 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:36 CEST" duration-ms="701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@7331196b]" started-at="2021-09-16T17:35:36 CEST" name="setUp" finished-at="2021-09-16T17:35:37 CEST" duration-ms="1290" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@7a7f2247]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionChrome(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@7331196b]" started-at="2021-09-16T17:35:37 CEST" name="verifySuccessfulSignUpActionChrome" data-provider="csvReader" finished-at="2021-09-16T17:35:38 CEST" duration-ms="1057" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=testFirstName2, lastName=testLastName2, password=testPassword2, mobile=testMobile2, description=Successfully registered user 2, email=test2@hlv.com, expectedMessage=User has been successfully registered., username=testUsername2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionChrome -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@7331196b]" started-at="2021-09-16T17:35:38 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:39 CEST" duration-ms="658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveSignUpTests -->
    </test> <!-- UserRegistrationTest1-CH -->
    <test started-at="2021-09-16T17:35:39 CEST" name="UserRegistrationTest2-FF" finished-at="2021-09-16T17:35:48 CEST" duration-ms="9047">
      <class name="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@539d019]" started-at="2021-09-16T17:35:39 CEST" name="setUp" finished-at="2021-09-16T17:35:42 CEST" duration-ms="3290" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4946dfde]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionFirefox(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@539d019]" started-at="2021-09-16T17:35:42 CEST" name="verifySuccessfulSignUpActionFirefox" data-provider="csvReader" finished-at="2021-09-16T17:35:43 CEST" duration-ms="615" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, firstName=testFirstName3, lastName=testLastName3, password=testPassword3, mobile=testMobile3, description=Successfully registered user 3, email=test3@hlv.com, expectedMessage=User has been successfully registered., username=testUsername3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionFirefox -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@539d019]" started-at="2021-09-16T17:35:43 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:43 CEST" duration-ms="817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@539d019]" started-at="2021-09-16T17:35:43 CEST" name="setUp" finished-at="2021-09-16T17:35:47 CEST" duration-ms="3190" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4946dfde]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfulSignUpActionFirefox(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@539d019]" started-at="2021-09-16T17:35:47 CEST" name="verifySuccessfulSignUpActionFirefox" data-provider="csvReader" finished-at="2021-09-16T17:35:47 CEST" duration-ms="509" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, firstName=testFirstName4, lastName=testLastName4, password=testPassword4, mobile=testMobile4, description=Successfully registered user 4, email=test4@hlv.com, expectedMessage=User has been successfully registered., username=testUsername4}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulSignUpActionFirefox -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.PositiveSignUpTests@539d019]" started-at="2021-09-16T17:35:47 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:35:48 CEST" duration-ms="623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.PositiveSignUpTests -->
    </test> <!-- UserRegistrationTest2-FF -->
  </suite> <!-- PositiveSignUpTestSuite -->
  <suite started-at="2021-09-16T17:35:28 CEST" name="DeleteAllUsersTestSuite" finished-at="2021-09-16T17:35:28 CEST" duration-ms="38">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:35:28 CEST" name="DeleteAllUsersTests" finished-at="2021-09-16T17:35:28 CEST" duration-ms="38">
      <class name="local.HLVTestApp.APITests.API_DeleteAllUsersTests">
        <test-method signature="API_DeleteAllUsers(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteAllUsersTests@77128536]" started-at="2021-09-16T17:35:28 CEST" name="API_DeleteAllUsers" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="36" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=Delete all users, body=All users removed, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteAllUsers -->
      </class> <!-- local.HLVTestApp.APITests.API_DeleteAllUsersTests -->
    </test> <!-- DeleteAllUsersTests -->
  </suite> <!-- DeleteAllUsersTestSuite -->
  <suite started-at="2021-09-16T17:35:28 CEST" name="DeleteByUsernameTestSuite" finished-at="2021-09-16T17:35:28 CEST" duration-ms="89">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:35:28 CEST" name="DeleteByUsernameTests" finished-at="2021-09-16T17:35:28 CEST" duration-ms="89">
      <class name="local.HLVTestApp.APITests.API_DeleteByUsernameTests">
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@673be18f]" started-at="2021-09-16T17:35:28 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="29" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=delete user - valid 1, body=User with username test1 is removed, username=test1, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@673be18f]" started-at="2021-09-16T17:35:28 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="16" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=delete user - valid 2, body=User with username test2 is removed, username=test2, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@673be18f]" started-at="2021-09-16T17:35:28 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="11" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, description=delete user - valid 3, body=User with username test3 is removed, username=test3, statusCode=200}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@673be18f]" started-at="2021-09-16T17:35:28 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, description=, body=, username=invalidUsername, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
        <test-method signature="API_DeleteByUsername(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_DeleteByUsernameTests@673be18f]" started-at="2021-09-16T17:35:28 CEST" name="API_DeleteByUsername" data-provider="csvReader" finished-at="2021-09-16T17:35:28 CEST" duration-ms="16" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=5, description=, body=, username=, statusCode=404}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_DeleteByUsername -->
      </class> <!-- local.HLVTestApp.APITests.API_DeleteByUsernameTests -->
    </test> <!-- DeleteByUsernameTests -->
  </suite> <!-- DeleteByUsernameTestSuite -->
  <suite started-at="2021-09-16T17:37:11 CEST" name="ExternalLoginLinkTestSuite" finished-at="2021-09-16T17:37:30 CEST" duration-ms="19034">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:37:11 CEST" name="ExternalLoginLinkTest1-CH" finished-at="2021-09-16T17:37:19 CEST" duration-ms="7160">
      <class name="local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:11 CEST" name="setUp" finished-at="2021-09-16T17:37:13 CEST" duration-ms="1262" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@77972964]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:13 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-16T17:37:13 CEST" duration-ms="241" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.facebook.com/, no=1, socialNetwork=Facebook}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:13 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:14 CEST" duration-ms="650" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:14 CEST" name="setUp" finished-at="2021-09-16T17:37:15 CEST" duration-ms="1250" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@77972964]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:15 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-16T17:37:15 CEST" duration-ms="232" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://twitter.com/, no=2, socialNetwork=Twitter}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://twitter.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://twitter.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:16 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:16 CEST" duration-ms="639" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:16 CEST" name="setUp" finished-at="2021-09-16T17:37:17 CEST" duration-ms="1247" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@77972964]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:17 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-16T17:37:18 CEST" duration-ms="231" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.plus.google.com/, no=3, socialNetwork=GooglePlus}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.plus.google.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.plus.google.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@1f010bf0]" started-at="2021-09-16T17:37:18 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:19 CEST" duration-ms="625" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests -->
    </test> <!-- ExternalLoginLinkTest1-CH -->
    <test started-at="2021-09-16T17:37:19 CEST" name="ExternalLoginLinkTest2-FF" finished-at="2021-09-16T17:37:30 CEST" duration-ms="11852">
      <class name="local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:19 CEST" name="setUp" finished-at="2021-09-16T17:37:22 CEST" duration-ms="2941" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@794f937a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:22 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-16T17:37:22 CEST" duration-ms="263" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.facebook.com/, no=1, socialNetwork=Facebook}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:22 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:23 CEST" duration-ms="630" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:23 CEST" name="setUp" finished-at="2021-09-16T17:37:26 CEST" duration-ms="2999" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@794f937a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:26 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-16T17:37:26 CEST" duration-ms="243" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://twitter.com/, no=2, socialNetwork=Twitter}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://twitter.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://twitter.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:26 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:27 CEST" duration-ms="644" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:27 CEST" name="setUp" finished-at="2021-09-16T17:37:29 CEST" duration-ms="2952" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@794f937a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLinkToSocialNetwork(java.util.Map)[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:29 CEST" name="verifyLinkToSocialNetwork" data-provider="csvReader" finished-at="2021-09-16T17:37:30 CEST" duration-ms="243" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedURL=https://www.plus.google.com/, no=3, socialNetwork=GooglePlus}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.plus.google.com/] but found [http://localhost:8080/#]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.plus.google.com/] but found [http://localhost:8080/#]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests.verifyLinkToSocialNetwork(ExternalLoginLinkTests.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkToSocialNetwork -->
        <test-method is-config="true" signature="tearDownAfterEach()[pri:0, instance:local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests@177bea38]" started-at="2021-09-16T17:37:30 CEST" name="tearDownAfterEach" finished-at="2021-09-16T17:37:30 CEST" duration-ms="660" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterEach -->
      </class> <!-- local.HLVTestApp.loginandsignuptests.ExternalLoginLinkTests -->
    </test> <!-- ExternalLoginLinkTest2-FF -->
  </suite> <!-- ExternalLoginLinkTestSuite -->
  <suite started-at="2021-09-16T17:37:31 CEST" name="HLV App Test Suites" finished-at="2021-09-16T17:37:31 CEST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- HLV App Test Suites -->
  <suite started-at="2021-09-16T17:35:24 CEST" name="RegisterUserTestSuite" finished-at="2021-09-16T17:35:27 CEST" duration-ms="3000">
    <groups>
    </groups>
    <test started-at="2021-09-16T17:35:24 CEST" name="RegisterUserTests" finished-at="2021-09-16T17:35:27 CEST" duration-ms="3000">
      <class name="local.HLVTestApp.APITests.API_RegisterUserTests">
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:24 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="2738" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, firstName=test1, lastName=test1, password=test1, description=valid username and password, body=, username=test1, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="43" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, firstName=test11111111111111111111111, lastName=test11, password=test11, description=Too long first name, body=First Name should be less than 15, username=test11, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="18" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=3, firstName=test111, lastName=test11111111111111111111111, password=test111, description=Too long last name, body=LAst Name should be less than 15, username=test111, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="33" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=4, firstName=test1111, lastName=test1111, password=test1111, description=User already exist, body=User with the specified username already exists!, username=test1, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="13" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=5, firstName=test11111, lastName=test11111, password=test11111, description=Too long username, body=Username must not be longer that 50 characters or shorter than 6 characters., username=test11111111111111111111111111111111111111111111111111111111, statusCode=400}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="26" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=6, firstName=test2, lastName=test2, password=test2, description=valid username and password 2, body=, username=test2, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="14" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=7, firstName=test3, lastName=test3, password=test3, description=valid username and password 3, body=, username=test3, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="14" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=8, firstName=test4, lastName=test4, password=test4, description=valid username and password 4, body=, username=test4, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
        <test-method signature="API_RegisterUser(java.util.Map)[pri:0, instance:local.HLVTestApp.APITests.API_RegisterUserTests@65b104b9]" started-at="2021-09-16T17:35:27 CEST" name="API_RegisterUser" data-provider="csvReader" finished-at="2021-09-16T17:35:27 CEST" duration-ms="11" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=9, firstName=test5, lastName=test5, password=test5, description=valid username and password 5, body=, username=test5, statusCode=201}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_RegisterUser -->
      </class> <!-- local.HLVTestApp.APITests.API_RegisterUserTests -->
    </test> <!-- RegisterUserTests -->
  </suite> <!-- RegisterUserTestSuite -->
</testng-results>
